theory:
  classy:
    extra_args:
      non_linear: hmcode
      YHe: 0.2454
      interaction_beta: 0
      super_schwarzschild_correction: 'yes'
      super_schw_amp: 0.0
      super_schw_deltaS: 0.03
      super_schw_gamma: 2.0
      super_schw_no_mapping: 0
likelihood:
  planck_2018_highl_plik.TTTEEE: null
  planck_2018_lowl.TT: null
  planck_2018_lowl.EE: null
  planck_2018_lensing.clik: null
  bao.sdss_dr12_consensus_full_shape: null
  bao.sdss_dr16_baoplus_qso: null
  bao.sdss_dr16_baoplus_elg: null
  bao.sdss_dr16_baoplus_lyauto: null
  bao.sdss_dr16_baoplus_lyxqso: null
  bao.sdss_dr7_mgs: null
  bao.sixdf_2011_bao: null
  sn.pantheonplus: null
  shoes_h0local.SH0ES_H0local:
    python_path: /Users/Bernard_1/holographic_mcmc/chains_schw
    H0_shoes: 73.04
    H0_shoes_err: 1.04
  desy3_likelihood_h0local.DESY3:
    python_path: /Users/Bernard_1/holographic_mcmc/chains_schw
    data_path: /Users/Bernard_1/holographic_mcmc/des_y3_data/likelihood/des-y3
params:
  omega_b:
    prior:
    - 0.019
    - 0.025
    ref: 0.02237
    proposal: 0.0003
    latex: \omega_b
  omega_cdm:
    prior:
    - 0.095
    - 0.145
    ref: 0.12
    proposal: 0.003
    latex: \omega_{cdm}
  H0:
    prior:
    - 60
    - 80
    ref: 68.0
    proposal: 1.0
    latex: H_0
  logA:
    prior:
    - 2.7
    - 3.4
    ref: 3.044
    proposal: 0.02
    latex: \log(10^{10}A_s)
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_s
  n_s:
    prior:
    - 0.9
    - 1.05
    ref: 0.9649
    proposal: 0.008
    latex: n_s
  tau_reio:
    prior:
    - 0.01
    - 0.12
    ref: 0.0544
    proposal: 0.01
    latex: \tau_{reio}
  A_IA:
    prior:
      min: -5.0
      max: 5.0
    ref: 0.0
    proposal: 0.5
    latex: A_{\rm IA}
  alpha_IA:
    prior:
      min: -5.0
      max: 5.0
    ref: 0.0
    proposal: 0.5
    latex: \alpha_{\rm IA}
  super_schw_Amap:
    prior:
      min: 0.0
      max: 10.0
    ref: 2.0
    proposal: 0.2
    latex: A_{\rm map}
  sigma8:
    latex: \sigma_8
  Omega_m:
    latex: \Omega_m
  H0_local:
    latex: H_0^{\rm loc}
  S8:
    derived: 'lambda sigma8, Omega_m: sigma8*np.sqrt(Omega_m/0.3)'
    latex: S_8
  S8_loc:
    derived: 'lambda sigma8, Omega_m, H0, H0_local: sigma8*np.sqrt(Omega_m*(H0/H0_local)**2/0.3)'
    latex: S_8^{\rm loc}
sampler:
  mcmc:
    Rminus1_stop: 0.01
    max_tries: 10000
    learn_proposal: true
    output_every: 60s
output: acdm_Amap_free
packages_path: /Users/Bernard_1/holographic_mcmc/packages
